### PR TITLE
fix: skip hash calculation when `crypto.subtle` is not available

### LINKED ISSUE #1498: Uploads stuck at 0%
Trying to upload, notification in corner is always stuck at 0%.  Tried different browsers, tried my phone.  Miniserver is running in a Docker image, so went to docker shell and I had write access to create a file in the upload directory.  Only thing I can think of is that it might need an https connection.  I'm simply using a local ip:port to connect right now.  That's all I need.  Just trying to transfer photos off my iphone.

```
1 uploads remaining...
Pending 1

CANCEL
0% - 65.19 KB - test.png
```

Turned verbose mode on but don't see anything useful:

```
miniserve v0.29.0
Thu, 05 Jun 2025 19:44:08 +0000 [INFO] starting 8 workers
Bound to [::]:8080, 0.0.0.0:8080
Serving path /share
Available at (non-exhaustive list):
    http://127.0.0.1:8080
    http://172.17.0.28:8080
    http://[::1]:8080

Thu, 05 Jun 2025 19:44:08 +0000 [INFO] Actix runtime found; starting in Actix runtime
Thu, 05 Jun 2025 19:44:08 +0000 [INFO] starting service: "actix-web-service-[::]:8080", workers: 8, listening on: [::]:8080
Thu, 05 Jun 2025 19:44:08 +0000 [INFO] starting service: "actix-web-service-0.0.0.0:8080", workers: 8, listening on: 0.0.0.0:8080
Thu, 05 Jun 2025 19:45:02 +0000 [INFO] 192.168.0.101 "GET / HTTP/1.1" 200 25124 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36" 0.006836
Thu, 05 Jun 2025 19:45:02 +0000 [INFO] 192.168.0.101 "GET /__miniserve_internal/style.css HTTP/1.1" 200 20990 "http://192.168.0.100:3912/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36" 0.000210
Thu, 05 Jun 2025 19:45:03 +0000 [INFO] 192.168.0.101 "POST /__miniserve_internal/api HTTP/1.1" 200 1 "http://192.168.0.100:3912/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36" 0.000319
Thu, 05 Jun 2025 19:51:20 +0000 [INFO] 192.168.0.101 "GET / HTTP/1.1" 200 25124 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36" 0.006795
Thu, 05 Jun 2025 19:51:20 +0000 [INFO] 192.168.0.101 "GET /__miniserve_internal/style.css HTTP/1.1" 200 20990 "http://192.168.0.100:3912/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36" 0.000224
Thu, 05 Jun 2025 19:51:20 +0000 [INFO] 192.168.0.101 "GET /__miniserve_internal/favicon.svg HTTP/1.1" 200 4048 "http://192.168.0.100:3912/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36" 0.000129
Thu, 05 Jun 2025 19:51:21 +0000 [INFO] 192.168.0.101 "POST /__miniserve_internal/api HTTP/1.1" 200 1 "http://192.168.0.100:3912/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36" 0.000218

```

```
docker run
  -d
  --name='miniserve-upload'
  --net='bridge'
  --pids-limit 2048
  -e TZ="America/New_York"
  -e 'MINISERVE_TITLE'='Uploads'
  -e 'MINISERVE_ALLOWED_UPLOAD_DIR'='/'
  -e 'MINISERVE_MEDIA_TYPE'='image'
  -e 'MINISERVE_PATH'='/share'
  -p '3912:8080/tcp'
  -v '/mnt/_uploads/':'/share':'rw'
  -e MINISERVE_VERBOSE=true
  -e MINISERVE_DIRS_FIRST=true
  -e MINISERVE_COLOR_SCHEME=archlinux
  -e MINISERVE_HIDE_VERSION_FOOTER=true
  -e MINISERVE_HIDE_THEME_SELECTOR=true 'svenstaro/miniserve:alpine'
3d841292f2598301b84066d55cdac97fc2a9b11bb125634d02c78e36c419064e
```

### PR DESCRIPTION
**Pull request by outloudvi**
fixes #1498

### CODE REVIEW

File: src/renderer.rs [hunk 1]
```diff
@@ -894,6 +894,10 @@ fn page_header(
                         });
 
                         async function get256FileHash(file) {
+                          if (!crypto.subtle) {
+                            // `crypto.subtle` is not available in nonsecure context (e.g. non-HTTPS LAN).
```
Comment (svenstaro) [inline src/renderer.rs:898]:
```suggestion
                            // `crypto.subtle` is not available in nonsecure context (e.g. non-HTTPS LAN).
                            // See https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle
```
